package:
  name: tomocuda
  version: '0.0.1'

source:
  git_url: https://github.com/kyuepublic/tomocuda.git
  
build:
  number: 0

requirements:
  build:
    - python
    - setuptools
    - cython
    - numpy

  run:
    - python
    - cython
    - numpy
    - scipy
    - scikit-image
    - tomopy
    
test:
  # Python imports
  imports:
    - tomocuda

about:
  home: https://github.com/kyuepublic/tomocuda
  license: BSD-3
  summary: 'Cuda function for median_filter and outlier_removal.'

